/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/canvas/circle/': RouteRecordInfo<'/canvas/circle/', '/canvas/circle', Record<never, never>, Record<never, never>>,
    '/canvas/codeRain/': RouteRecordInfo<'/canvas/codeRain/', '/canvas/codeRain', Record<never, never>, Record<never, never>>,
    '/canvas/line/': RouteRecordInfo<'/canvas/line/', '/canvas/line', Record<never, never>, Record<never, never>>,
    '/canvas/musicWaveform/': RouteRecordInfo<'/canvas/musicWaveform/', '/canvas/musicWaveform', Record<never, never>, Record<never, never>>,
    '/canvas/tree/': RouteRecordInfo<'/canvas/tree/', '/canvas/tree', Record<never, never>, Record<never, never>>,
    '/compoent/heart/': RouteRecordInfo<'/compoent/heart/', '/compoent/heart', Record<never, never>, Record<never, never>>,
    '/compoent/imageZoom/': RouteRecordInfo<'/compoent/imageZoom/', '/compoent/imageZoom', Record<never, never>, Record<never, never>>,
    '/compoent/love/': RouteRecordInfo<'/compoent/love/', '/compoent/love', Record<never, never>, Record<never, never>>,
    '/snack/': RouteRecordInfo<'/snack/', '/snack', Record<never, never>, Record<never, never>>,
  }
}
